#include "Board.h"




Board::Board(int len, int wid)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CA2 begin
{
}
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CA2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Board::draw(ostream* o)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CA6 begin
{
}
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CA6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Board::placePiece(Piece* p, Square* s)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CAA begin
{
}
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CAA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Board::movePiece(Square* s, Square* d)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CAF begin
{
}
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CAF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Square* Board::getSquare(int r, int c)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CB5 begin
{
}
// section 127-0-1-1--71e28881:1501edd9e87:-8000:0000000000000CB5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
