#include "Chess.h"




Chess::Chess()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7e1121e1:1501ce147c7:-8000:0000000000000A7B begin
{
}
// section 127-0-1-1--7e1121e1:1501ce147c7:-8000:0000000000000A7B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Chess::setup()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000AD4 begin
{
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000AD4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Chess::isOver()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000AD6 begin
{
    return false;
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000AD6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Square* Chess::getSquare(istream &is)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000AD8 begin
{
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000AD8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
