#include "Game.h"




void Game::play()
{
	setup();
	while(!isOver()){

	}
}
// section -64--88--76-1-2bccb5:150156bc0c1:-8000:000000000000087F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Game::movePiece(Square* s, Square* d)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--7e1121e1:1501ce147c7:-8000:0000000000000A7E begin
{
    return false;
}
// section 127-0-1-1--7e1121e1:1501ce147c7:-8000:0000000000000A7E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Game::~Game()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000ADE begin
{
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000ADE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
