#include "Piece.h"




Piece::Piece(String colour, char symbol)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FE2 begin
{
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FE2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Piece::isAlive()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--598b1a0d:150210e36d6:-8000:0000000000000ACE begin
{
    return false;
}
// section 127-0-1-1--598b1a0d:150210e36d6:-8000:0000000000000ACE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Piece::kill()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--598b1a0d:150210e36d6:-8000:0000000000000AD2 begin
{
}
// section 127-0-1-1--598b1a0d:150210e36d6:-8000:0000000000000AD2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
