#include "Square.h"




Square::Square(int row, int col)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FC9 begin
{
    return 0;
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FC9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char Square::symbol()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FCD begin
{
    return 'x';
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FCD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Square::setPiece(Piece* p)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FCF begin
{
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FCF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Piece* Square::getPiece()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FD1 begin
{
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FD1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Piece* Square::removePiece()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FD3 begin
{
}
// section 127-0-1-1-56044bb9:150212358ac:-8000:0000000000000FD3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
